### ISSUE TITLE
Target -1 is out of bounds

### ISSUE THREAD

**Issue by 126zz6** [nickuntitled/pyramid_aggregate_head_pose_estimation#1]
return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
IndexError: Target -1 is out of bounds.
How can I solve this problem

**Comment by nickuntitled** [comment]
Hello @126zz6 for creating an issue about _"Target -1 is out of bounds"_.

From the issue, the IndexError during using torch._C._nn.cross_entropy_loss is from the target (or label) index is outside the range (which means the head pose labels are outside the range -99 and 99 degrees).

I wrote the code that it caused an error like that below.

```
test = torch.Tensor([[0, 0.5, 0.2], [0.1, 0.3, 0.4]])
gt = torch.LongTensor([-1, 1])
output = class_criterion(test, gt)
```

It showed.

```
IndexError: Target -1 is out of bounds.
```

Next, I saw the CrossEntropyLoss was available on the HPE training code (**train.py**). When training the model, you have to follow the instruction inside **README.md** such as 
- [How to prepare](https://github.com/nickuntitled/pyramid_aggregate_head_pose_estimation/tree/main?tab=readme-ov-file#how-to-prepare)
- How to train below each dataset name ([300W_LP](https://github.com/nickuntitled/pyramid_aggregate_head_pose_estimation/tree/main?tab=readme-ov-file#300w_lp-1), [BIWI](https://github.com/nickuntitled/pyramid_aggregate_head_pose_estimation/tree/main?tab=readme-ov-file#biwi-1), or [DAD-3DHeads](https://github.com/nickuntitled/pyramid_aggregate_head_pose_estimation/tree/main?tab=readme-ov-file#dad-3dheads-1)).

The filename list used for training (**argument --filename_list**) is available inside the folder
- **datasets/300W_LP** which has [300wlp_list.txt](https://github.com/nickuntitled/pyramid_aggregate_head_pose_estimation/blob/main/datasets/300W_LP/300wlp_list.txt)
- **datasets/BIWI** which has [biwi_list.txt](https://github.com/nickuntitled/pyramid_aggregate_head_pose_estimation/blob/main/datasets/BIWI/biwi_list.txt), [biwi_train_list.txt](https://github.com/nickuntitled/pyramid_aggregate_head_pose_estimation/blob/main/datasets/BIWI/biwi_train_list.txt), and [biwi_test_list.txt](https://github.com/nickuntitled/pyramid_aggregate_head_pose_estimation/blob/main/datasets/BIWI/biwi_test_list.txt).
- or **datasets/DAD** which has [train.json](https://github.com/nickuntitled/pyramid_aggregate_head_pose_estimation/blob/main/datasets/DAD/train.json).

However, if you want to create your own filename list, you have to make sure that each head pose values (yaw, pitch, and roll) is between -99 and 99 degrees, otherwise, you will see the error **Target -1 is out of bounds**.
